# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Daily test / OS ${{ matrix.os }} / Flutter Version ${{ matrix.flutter-version }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        flutter-version: ['3.x']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checks-out repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0

      - run: supabase start

      - name: Instlal junitreport
        run: dart pub global activate junitreport
        
      - name: Run tests
        run: flutter test --machine | tojunit --output report.xml
